### ISSUE TITLE
Question about running with run.py

### ISSUE THREAD

**Issue by HYDesmondLiu** [Advitya17/AutoBrickify#1]
Hi,
   I have followed the instructions with `python run.py` and the error message I got is as the first block shown below.
   If I change the input file to data/table_603_v1.csv then the error message is the second block shown below. Could you advise me what have I done wrong?
   
```
Traceback (most recent call last):
  File "../brick-builder/make.py", line 178, in <module>
    g = generate(pairs)
  File "../brick-builder/make.py", line 154, in generate
    _g = b.build(csv_file, has_header=True)
  File "../brick-builder/make.py", line 99, in build
    g.bind(pfx, ns)
AttributeError: 'Graph' object has no attribute 'bind'
```
```
Traceback (most recent call last):
  File "run.py", line 44, in <module>
    run(action)
  File "run.py", line 33, in run
    filename = automatic_OR(filename='output.ttl')
  File "/home/hsinyu/YYY_Capstone/01_AutoBrickify/AutoBrickify/src/execute.py", line 127, in automatic_OR
    df[split_cols] = col_split_res
  File "/home/hsinyu/hyliu_Python/lib/python3.6/site-packages/pandas/core/frame.py", line 3034, in __setitem__
    self._setitem_array(key, value)
  File "/home/hsinyu/hyliu_Python/lib/python3.6/site-packages/pandas/core/frame.py", line 3060, in _setitem_array
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
```

**Comment by Advitya17** [comment]
Hi, sorry for the delayed response. That's because the point label column name in this dataset isn't `jci_name` but actually just `name` if you look at the dataset.

Currently, our tool assumes there's one column for point labels. In this case, it seems the AHUs, VAVs, Zones info are in the `name` column but the BrickClass info is actually contained in `jci_name`.

To mitigate cases like these, we could technically tweak the `point_label_format` argument to accept a dictionary instead of a list, such that:

1. the key of the dictionary would be a column name (there may be one or more keys depending on use case, in this case there'll be 2 keys), and 
2. the value will be either:
(a) a list with the same length as when separated by a delimiter containing elements related to either null, string or list as described in the config README documentation for the column names.
(b) a string column name for `jci_name` in this dataset, which just contains the sensors.

The interface may get a little complicated/nested with these kinds of granular specifications, but these may still be important for end-to-end automation and to eliminate manual human intervention while running the tool. Me and @devanshuDesai can discuss the interface for the same and accordingly modify the tool and attach documentation. 

For now, the tool should work with any file that has one column with all the point label info. Just be sure to modify any other configuration values depending on the nature of your dataset.

Let me know how this sounds and/or any recommendations you may have for us as well.

**Comment by Advitya17** [comment]
Hi @HYDesmondLiu, we got a chance to look at this case. 

1. First up, if you notice, the `jci_name` column basically has the same equivalent brick classes as the `name` column, so technically all the point labels info is already contained in the `name` column. Hence, at this time we still maintain the simplifying assumption that all the point labels info is contained inside one column. Please point out any use cases if this assumption is violated.

2. We essentially prepared a configurations file, tested and validated the code with the 603 file, and pushed it to GitHub. If you notice the `configs/data_params.json` file, our point label format this time is 

`"point_label_format": ["UpstreamAHU", ["ZoneName", "VAVName"], "BrickClass"]`

This is because the metadata string / point label looks like `NAE-103/FCB.Local Application.SA2-T`. If you split on a '.', you get 3 elements, hence 3 elements in the overall `point_label_format` list. This technically doesn't have the VAV info, hence we replicate the Zone column to make VAV identifiers (exactly like the tutorial :)) and hence have the 2nd element (i.e. at index 1) as a list in itself which has the column names that'll be taking up the same semantic value. 

3. We acknowledge the insights you provided related to additional columns which may have info for better BrickClass predictions. Hence, we added a param in the configs file called `additional_brick_class_info_columns` which takes a list (empty list in the case of no additional column for BrickClass insights) of additional columns useful for brick class inference. (Though this dataset may not be ideal for testing in general as it has a lot of null values and only has 41 rows. May wanna use a bigger dataset)

If you observe the 603 preprocessed data (saved in the same file path as the local data), that also has the keywords (from the specified `description` and `unit` columns) stitched into the BrickClass, if you wish to validate the result. (Though this dataset may not be ideal for testing in general as it has a lot of null values and only has 41 rows. May wanna use a bigger dataset)

4. For further testing with different data files, please refer to the usage instructions for constructing the appropriate configurations file. Please let us know if you have any questions. Thanks a lot!

--
